// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TActImgDatum
{
    public int FImgId { get; set; }

    public int? FActId { get; set; }

    public string FImgDescription { get; set; }

    public string FActImgName { get; set; }

    public string FActImgPath { get; set; }

    public byte[] FImgByte { get; set; }

    public virtual TActInformation FAct { get; set; }
}