// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TActDetail
{
    public int FActDetailId { get; set; }

    public int? FActId { get; set; }

    public int? FStatusId { get; set; }

    public string FDisplayId { get; set; }

    public string FStartDate { get; set; }

    public string FEndDate { get; set; }

    public string FRegStartDate { get; set; }

    public string FRegDeadline { get; set; }

    public virtual TActInformation FAct { get; set; }
}