// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TAdvertisement
{
    public int FAdId { get; set; }

    public string FAdName { get; set; }

    public string UserId會員id { get; set; }

    public string FAdType { get; set; }

    public string FImagePath { get; set; }

    public string FLink { get; set; }

    public int? FUserId { get; set; }

    public long? FClickCount { get; set; }
}