// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TCart
{
    public int FCartItemId { get; set; }

    public int? FUserId { get; set; }

    public int? FItemQuantity { get; set; }

    public int? FProductId { get; set; }
}