// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TDonation
{
    public int FDonationId { get; set; }

    public int? FUserId { get; set; }

    public string FDonationDate { get; set; }

    public decimal? FAmount { get; set; }
}