// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class THobby
{
    public int FHobbyId { get; set; }

    public string FHobbyName { get; set; }

    public virtual ICollection<THobbyPrefer> THobbyPrefers { get; set; } = new List<THobbyPrefer>();

    public virtual ICollection<TUserHobby> TUserHobbies { get; set; } = new List<TUserHobby>();
}