// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TKeyword
{
    public int FKeywordDetailId { get; set; }

    public int? FProdCategoryId { get; set; }

    public string FProdKeyword { get; set; }
}