// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TLight
{
    public int? FLightId { get; set; }

    public int? FUserId { get; set; }

    public string FLightUser { get; set; }

    public DateOnly? FLightBirthday { get; set; }

    public string FLightAddress { get; set; }

    public DateOnly FLightStart { get; set; }

    public DateOnly? FLightEnd { get; set; }

    public bool? FLightStatus { get; set; }
}