// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TManager
{
    public int FManagerId { get; set; }

    public string FManagerName { get; set; }

    public string FManagerEmail { get; set; }

    public string FManagerPassword { get; set; }

    public string FManagerPhone { get; set; }

    public string FManagerPasswordSalt { get; set; }

    public string FManagerAddress { get; set; }

    public bool FManagerState { get; set; }

    public bool FManagerProductState { get; set; }

    public bool FManagerOrderState { get; set; }

    public bool FManagerActivityState { get; set; }

    public bool FManagerServiceState { get; set; }

    public bool FManagerMatchState { get; set; }

    public bool FManagerAdvertisementState { get; set; }

    public bool FManagerPermissionState { get; set; }

    public bool FManagerUserState { get; set; }
}