// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TMatch
{
    public int FMatchId { get; set; }

    public int? FFrom { get; set; }

    public int? FTo { get; set; }

    public string FMatchDate { get; set; }

    public string FUpdateDate { get; set; }

    public string FMessage { get; set; }

    public string FMessageStatus { get; set; }

    public int? FStatusId { get; set; }

    public virtual TUserPrefer FFromNavigation { get; set; }

    public virtual TStatus FStatus { get; set; }

    public virtual TUserPrefer FToNavigation { get; set; }
}