// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TOrder
{
    public int FOrderId { get; set; }

    public int? FUserId { get; set; }

    public string FOrderDate { get; set; }

    public string FOrderStatus { get; set; }

    public bool? FPaymentStatus { get; set; }

    public bool? FShippingStatus { get; set; }

    public bool? FServiceStatus { get; set; }

    public string FPaymentInfo { get; set; }

    public string FRecepientName { get; set; }

    public string FRecepientAddress { get; set; }

    public string FRecepientPhone { get; set; }

    public string FRecepientEmail { get; set; }

    public string FOrderRemarks { get; set; }

    public string FShippingInfo { get; set; }

    public string FReturnInfo { get; set; }

    public decimal? FTotalPrice { get; set; }
}