// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TOrderDetail
{
    public int FOrderDetailId { get; set; }

    public int? FOrderId { get; set; }

    public int? FProductId { get; set; }

    public int? FQuantity { get; set; }

    public decimal? FPrice { get; set; }

    public string FReviewDate { get; set; }

    public int? FReviewScore { get; set; }

    public string FProductReview { get; set; }
}