// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TPermission
{
    public int FPermissionId { get; set; }

    public string FPermissionName { get; set; }

    public string FPermissionDescription { get; set; }
}