// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TPostReply
{
    public int ReId { get; set; }

    public string ReContent { get; set; }

    public DateTime Created { get; set; }

    public string UserId { get; set; }

    public int PoId { get; set; }

    public string ImageUrl { get; set; }
}