// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TPost
{
    public int PoId { get; set; }

    public string PoTitle { get; set; }

    public string PoContent { get; set; }

    public DateTime Create { get; set; }

    public string UserId { get; set; }

    public int ForId { get; set; }

    public string YoutubeUrl { get; set; }

    public string ImageUrl { get; set; }

    public string Font { get; set; }

    public int? ClickCount { get; set; }

    public int? CommentCount { get; set; }

    public string Tag { get; set; }

    public string Comments { get; set; }

    public virtual TForum For { get; set; }
}