// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TProduct
{
    public int FProductId { get; set; }

    public string FProdName { get; set; }

    public string FProdDescription { get; set; }

    public decimal? FProdPrice { get; set; }

    public int? FProdStock { get; set; }

    public string FProdCreateAt { get; set; }

    public string FProdUpdateAt { get; set; }

    public int? FCompanyId { get; set; }

    public decimal? FProdSellingPrice { get; set; }

    public string FProdImage { get; set; }

    public bool? FProdStatus { get; set; }

    public string FProdPromoStartDate { get; set; }

    public string FProdPromoEndDate { get; set; }

    public string FProdCategory { get; set; }

    public virtual ICollection<TUserLike> TUserLikes { get; set; } = new List<TUserLike>();
}