// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TProdCategory
{
    public int FProdCategoryId { get; set; }

    public string FProdCatName { get; set; }
}