// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TQuestionAnswer
{
    public int FQuestionId { get; set; }

    public int? FQuestionTypesId { get; set; }

    public string FQuestion { get; set; }

    public string FAnswer { get; set; }
}