// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TRegDetail
{
    public int FRegDetailsId { get; set; }

    public int? FRegId { get; set; }

    public string FRegName { get; set; }

    public string FRegTel { get; set; }

    public string FRegEmail { get; set; }

    public string FRecipientAddress { get; set; }

    public virtual TActEventReg FReg { get; set; }
}