// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TServiceDetail
{
    public int FServiceId { get; set; }

    public int? FUserId { get; set; }

    public int? FOrderId { get; set; }

    public string FTargetName { get; set; }

    public string FServicePerson { get; set; }

    public string FServiceDescription { get; set; }

    public int? FProductId { get; set; }

    public string FServiceDate { get; set; }
}