// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TStatus
{
    public int FStatusId { get; set; }

    public string Status { get; set; }

    public string FCategory { get; set; }

    public virtual ICollection<TActEventReg> TActEventRegs { get; set; } = new List<TActEventReg>();

    public virtual ICollection<TMatch> TMatches { get; set; } = new List<TMatch>();
}