// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TStockDetail
{
    public int FStockDetailId { get; set; }

    public int? FProductId { get; set; }

    public int? FChangeAmount { get; set; }

    public string FChangeType { get; set; }

    public string FChangeDateTime { get; set; }
}