// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TTraitsPrefer
{
    public int FTraitsPreferId { get; set; }

    public int? FUserPreferId { get; set; }

    public int? FTraitsId { get; set; }

    public virtual TTrait FTraits { get; set; }

    public virtual TUserPrefer FUserPrefer { get; set; }
}