// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TTrait
{
    public int FTraitsId { get; set; }

    public string FTraitsName { get; set; }

    public virtual ICollection<TTraitsPrefer> TTraitsPrefers { get; set; } = new List<TTraitsPrefer>();

    public virtual ICollection<TUserTrait> TUserTraits { get; set; } = new List<TUserTrait>();
}