// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TUpcomingAct
{
    public int FAnnouncementId { get; set; }

    public int? FActId { get; set; }

    public string FActUrl { get; set; }

    public byte[] FAnnounceImg { get; set; }

    public string FApplicationDate { get; set; }

    public string FReleaseDate { get; set; }

    public string FRemovalDate { get; set; }
}