// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TUserPrefer
{
    public int FUserPreferId { get; set; }

    public int? FUserId { get; set; }

    public string FCity { get; set; }

    public decimal? FHeight { get; set; }

    public int? FAge { get; set; }

    public decimal FMaxHeight { get; set; }

    public decimal FMinHeight { get; set; }

    public int FMaxAge { get; set; }

    public int FMinAge { get; set; }

    public bool FGender { get; set; }

    public string FPhotoPath { get; set; }

    public string FInfo { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<THobbyPrefer> THobbyPrefers { get; set; } = new List<THobbyPrefer>();

    public virtual ICollection<TMatch> TMatchFFromNavigations { get; set; } = new List<TMatch>();

    public virtual ICollection<TMatch> TMatchFToNavigations { get; set; } = new List<TMatch>();

    public virtual ICollection<TTraitsPrefer> TTraitsPrefers { get; set; } = new List<TTraitsPrefer>();

    public virtual ICollection<TUserHobby> TUserHobbies { get; set; } = new List<TUserHobby>();

    public virtual ICollection<TUserTrait> TUserTraits { get; set; } = new List<TUserTrait>();
}