// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TUserLike
{
    public int FUserLikeId { get; set; }

    public int? FUserId { get; set; }

    public int? FProductId { get; set; }

    public virtual TProduct FProduct { get; set; }

    public virtual TUser FUser { get; set; }
}