// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aprojectbackend.Models;

public partial class TUser
{
    public int FUserId { get; set; }

    public string FUserEmail { get; set; }

    public string FUserPassword { get; set; }

    public string FUserName { get; set; }

    public string FUserPhone { get; set; }

    public bool? FUserGender { get; set; }

    public string FUserAddress { get; set; }

    public DateOnly? FUserBirthdate { get; set; }

    public int FUserStateId { get; set; }

    public string FUserImage { get; set; }

    public string FUserPasswordSalt { get; set; }

    public string FUserNickName { get; set; }

    public virtual TUserState FUserState { get; set; }

    public virtual ICollection<TUserLike> TUserLikes { get; set; } = new List<TUserLike>();

    public virtual ICollection<TUserPrefer> TUserPrefers { get; set; } = new List<TUserPrefer>();
}